nodeLinker: node-modules
npmScopes:
  remix-run:
    npmAlwaysAuth: true
    npmAuthToken: ${REMIX_REGISTRY_TOKEN}
    npmRegistryServer: https://npm.remix.run
yarnPath: .yarn/releases/yarn-2.4.1.cjs
